#ifndef EARTHVIEW_WORLD_SPATIAL3D_OSGB_COFING_H
#define EARTHVIEW_WORLD_SPATIAL3D_OSGB_COFING_H

#include "core/global.h"

#ifdef EV_BUILD_SPATIAL3D_OSGB
#define EV_Spatial3D_OSGB_DLL EV_DLL_EXPORT
#else
#define EV_Spatial3D_OSGB_DLL EV_DLL_IMPORT
#endif

#endif