#ifndef EARTHVIEW_WORLD_SPATIAL2D_SPATIALTHEMEEXPORTS_H
#define EARTHVIEW_WORLD_SPATIAL2D_SPATIALTHEMEEXPORTS_H

#ifdef EV_BULID_SPATIALTHEME
#define EV_SPATIALTHEME_DLL EV_DLL_EXPORT
#else
#define EV_SPATIALTHEME_DLL EV_DLL_IMPORT
#endif

#include "core/global.h"
#endif
