using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

public static class EV_Spatial_ChartProxy_ClassFactory
{
	public static void RegisterAll()
	{
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxColorMode", new EarthView.World.Spatial.SystemUI.ChartEntryBoxColorModeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxColorModeProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxColorModeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxColorMode3D", new EarthView.World.Spatial.SystemUI.ChartEntryBoxColorMode3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxColorMode3DProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxColorMode3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxLabelType", new EarthView.World.Spatial.SystemUI.ChartEntryBoxLabelTypeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxLabelTypeProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxLabelTypeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxLabelType3D", new EarthView.World.Spatial.SystemUI.ChartEntryBoxLabelType3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxLabelType3DProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxLabelType3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSaftyContour", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSaftyContourClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSaftyContourProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSaftyContourClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSaftyContour3D", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSaftyContour3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSaftyContour3DProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSaftyContour3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSymbolType", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSymbolTypeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSymbolTypeProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSymbolTypeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSymbolType3D", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSymbolType3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxSymbolType3DProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxSymbolType3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxViewCategory", new EarthView.World.Spatial.SystemUI.ChartEntryBoxViewCategoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxViewCategoryProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxViewCategoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxViewCategory3D", new EarthView.World.Spatial.SystemUI.ChartEntryBoxViewCategory3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::SystemUI::CChartEntryBoxViewCategory3DProxy", new EarthView.World.Spatial.SystemUI.ChartEntryBoxViewCategory3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBasicView", new EarthView.World.Spatial2D.Controls.CommandChartBasicViewClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBasicViewProxy", new EarthView.World.Spatial2D.Controls.CommandChartBasicViewClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBasicView3D", new EarthView.World.Spatial3D.Controls.CommandChartBasicView3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBasicView3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartBasicView3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBlackBackColor", new EarthView.World.Spatial2D.Controls.CommandChartBlackBackColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBlackBackColorProxy", new EarthView.World.Spatial2D.Controls.CommandChartBlackBackColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBlackBackColor3D", new EarthView.World.Spatial3D.Controls.CommandChartBlackBackColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBlackBackColor3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartBlackBackColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBlurRelationship", new EarthView.World.Spatial2D.Controls.CommandChartBlurRelationshipClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBlurRelationshipProxy", new EarthView.World.Spatial2D.Controls.CommandChartBlurRelationshipClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBlurRelationship3D", new EarthView.World.Spatial3D.Controls.CommandChartBlurRelationship3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBlurRelationship3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartBlurRelationship3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBrightColor", new EarthView.World.Spatial2D.Controls.CommandChartBrightColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartBrightColorProxy", new EarthView.World.Spatial2D.Controls.CommandChartBrightColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBrightColor3D", new EarthView.World.Spatial3D.Controls.CommandChartBrightColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartBrightColor3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartBrightColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartChineseLabel", new EarthView.World.Spatial2D.Controls.CommandChartChineseLabelClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartChineseLabelProxy", new EarthView.World.Spatial2D.Controls.CommandChartChineseLabelClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartChineseLabel3D", new EarthView.World.Spatial3D.Controls.CommandChartChineseLabel3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartChineseLabel3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartChineseLabel3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartDuskColor", new EarthView.World.Spatial2D.Controls.CommandChartDuskColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartDuskColorProxy", new EarthView.World.Spatial2D.Controls.CommandChartDuskColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartDuskColor3D", new EarthView.World.Spatial3D.Controls.CommandChartDuskColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartDuskColor3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartDuskColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartEnglishLabel", new EarthView.World.Spatial2D.Controls.CommandChartEnglishLabelClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartEnglishLabelProxy", new EarthView.World.Spatial2D.Controls.CommandChartEnglishLabelClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartEnglishLabel3D", new EarthView.World.Spatial3D.Controls.CommandChartEnglishLabel3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartEnglishLabel3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartEnglishLabel3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartNightColor", new EarthView.World.Spatial2D.Controls.CommandChartNightColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartNightColorProxy", new EarthView.World.Spatial2D.Controls.CommandChartNightColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartNightColor3D", new EarthView.World.Spatial3D.Controls.CommandChartNightColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartNightColor3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartNightColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartOtherView", new EarthView.World.Spatial2D.Controls.CommandChartOtherViewClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartOtherViewProxy", new EarthView.World.Spatial2D.Controls.CommandChartOtherViewClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartOtherView3D", new EarthView.World.Spatial3D.Controls.CommandChartOtherView3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartOtherView3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartOtherView3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour10M", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour10MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour10MProxy", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour10MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour10M3D", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour10M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour10M3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour10M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour20M", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour20MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour20MProxy", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour20MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour20M3D", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour20M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour20M3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour20M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour30M", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour30MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour30MProxy", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour30MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour30M3D", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour30M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour30M3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour30M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour5M", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour5MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSaftyContour5MProxy", new EarthView.World.Spatial2D.Controls.CommandChartSaftyContour5MClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour5M3D", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour5M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSaftyContour5M3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartSaftyContour5M3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSimpleSymbol", new EarthView.World.Spatial2D.Controls.CommandChartSimpleSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSimpleSymbolProxy", new EarthView.World.Spatial2D.Controls.CommandChartSimpleSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSimpleSymbol3D", new EarthView.World.Spatial3D.Controls.CommandChartSimpleSymbol3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSimpleSymbol3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartSimpleSymbol3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSpecificRelationship", new EarthView.World.Spatial2D.Controls.CommandChartSpecificRelationshipClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartSpecificRelationshipProxy", new EarthView.World.Spatial2D.Controls.CommandChartSpecificRelationshipClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSpecificRelationship3D", new EarthView.World.Spatial3D.Controls.CommandChartSpecificRelationship3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartSpecificRelationship3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartSpecificRelationship3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartStandardView", new EarthView.World.Spatial2D.Controls.CommandChartStandardViewClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartStandardViewProxy", new EarthView.World.Spatial2D.Controls.CommandChartStandardViewClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartStandardView3D", new EarthView.World.Spatial3D.Controls.CommandChartStandardView3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartStandardView3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartStandardView3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartTraditionalSymbol", new EarthView.World.Spatial2D.Controls.CommandChartTraditionalSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartTraditionalSymbolProxy", new EarthView.World.Spatial2D.Controls.CommandChartTraditionalSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartTraditionalSymbol3D", new EarthView.World.Spatial3D.Controls.CommandChartTraditionalSymbol3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartTraditionalSymbol3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartTraditionalSymbol3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartWhiteBackColor", new EarthView.World.Spatial2D.Controls.CommandChartWhiteBackColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial2D::Controls::CCommandChartWhiteBackColorProxy", new EarthView.World.Spatial2D.Controls.CommandChartWhiteBackColorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartWhiteBackColor3D", new EarthView.World.Spatial3D.Controls.CommandChartWhiteBackColor3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommandChartWhiteBackColor3DProxy", new EarthView.World.Spatial3D.Controls.CommandChartWhiteBackColor3DClassFactory());
	}
}

