#ifndef EARTHVIEW_WORLD_RASTERANALYSISCONFIG_H
#define EARTHVIEW_WORLD_RASTERANALYSISCONFIG_H

#include "core/core_api.h"

#ifdef EV_RASTERANALYSIS_EXPORTS
#define EV_RASTERANALYSIS_DLL EV_DLL_EXPORT
#else
#define EV_RASTERANALYSIS_DLL EV_DLL_IMPORT
#endif

#endif