#ifndef _SPATIAL3D_CALCULATOR_CONFIG_H
#define _SPATIAL3D_CALCULATOR_CONFIG_H

#include <core/global.h>

#ifdef EV_BUILD_SPATIAL3D_CALCULATOR
#define EV_SPATIAL3DCALCULATOR_DLL EV_DLL_EXPORT
#else
#define EV_SPATIAL3DCALCULATOR_DLL EV_DLL_IMPORT

#endif

#endif