#ifndef EARTHVIEW_WORLD_SPATIAL2D_RENDERER_CONFIG_H
#define EARTHVIEW_WORLD_SPATIAL2D_RENDERER_CONFIG_H
#include "core/global.h"

#ifdef EV_BUILD_SPATIAL2DDISPLAY
#define EV_SPATIAL2DDISPLAY_DLL EV_DLL_EXPORT
#else
#define EV_SPATIAL2DDISPLAY_DLL EV_DLL_IMPORT
#endif

#endif
