#ifndef _DATASOURCETREEEXPORT_INCLUDE__
#define _DATASOURCETREEEXPORT_INCLUDE__
#include "core/global.h"

#ifdef  EV_BUILD_DATASOURCETREE
#define DATASOURCETREE_DLL EV_DLL_EXPORT
#else
#define DATASOURCETREE_DLL EV_DLL_IMPORT
#endif

#endif // _DATASOURCETREEEXPORT_INCLUDE__
