#ifndef _VIEWPANELTREEEXPORT_INCLUDE__
#define _VIEWPANELTREEEXPORT_INCLUDE__

#ifdef  EV_BUILD_VIEWPANEL
#define EXPORT_DLL Q_DECL_EXPORT
#else
#define EXPORT_DLL Q_DECL_IMPORT
#endif

#endif // _VIEWPANELTREEEXPORT_INCLUDE__
