#ifndef __Custom_Config_H_
#define __Custom_Config_H_
/// CMake auto-generated configuration options
/* #undef EV_STATIC_LIB */
#if EV_PLATFORM != EV_PLATFORM_ANDROID
#define EV_BUILD_RENDERSYSTEM_D3D9
/* #	undef EV_BUILD_RENDERSYSTEM_D3D10 */
/* #	undef EV_BUILD_RENDERSYSTEM_D3D11 */
#define EV_BUILD_RENDERSYSTEM_GL
/* #	undef EV_BUILD_RENDERSYSTEM_GLES */
///#	define EV_BUILD_PLUGIN_BSP
#define EV_BUILD_PLUGIN_OCTREE
///#define EV_BUILD_PLUGIN_PCZ
#define EV_BUILD_PLUGIN_PFX
#define EV_BUILD_PLUGIN_CG
#else
#define EV_BUILD_PLUGIN_OCTREE
#define EV_BUILD_PLUGIN_PFX
#define EV_BUILD_RENDERSYSTEM_GLES2
#endif

//#define EV_DOUBLE_PRECISION 0
#define EV_NO_FREEIMAGE 0
#define EV_NO_DDS_CODEC 0
#define EV_NO_PVRTC_CODEC 0
#define EV_NO_ZIP_ARCHIVE 0
#define EV_NO_VIEWPORT_ORIENTATIONMODE 0
#define EV_USE_NEW_COMPILERS 1
#define EV_PROFILING 0
#ifndef RTSHADER_SYSTEM_BUILD_CORE_SHADERS
#define RTSHADER_SYSTEM_BUILD_CORE_SHADERS
#endif
#ifndef RTSHADER_SYSTEM_BUILD_EXT_SHADERS
#define RTSHADER_SYSTEM_BUILD_EXT_SHADERS
#endif
#ifdef EV_OS_IOS
#undef  EV_NO_VIEWPORT_ORIENTATIONMODE
#define  EV_NO_VIEWPORT_ORIENTATIONMODE 1
#define EV_STATIC_LIB
#define  EV_NO_GLES2_CG_SUPPORT 1
#define EV_NO_GLES2_GLSL_OPTIMISER 1
#define EV_BUILD_RENDERSYSTEM_GLES2
#define EV_STATIC_OctreeSceneManager
#define EV_STATIC_ParticleFX
#undef  EV_STATIC_GLES
#define EV_STATIC_GLES2
#define USE_RTSHADER_SYSTEM
#undef  EV_BUILD_PLUGIN_CG
#undef  EV_BUILD_RENDERSYSTEM_GL
#undef  EV_BUILD_RENDERSYSTEM_D3D9
#endif
#endif

