#ifndef EARTHVIEW_WORLD_SPATIAL2D_ATLAS_SPATIAL2DATLASCONFIG_H
#define EARTHVIEW_WORLD_SPATIAL2D_ATLAS_SPATIAL2DATLASCONFIG_H
#include "core/core_api.h"

#ifdef EV_BUILD_SPATIAL2DATLAS
#define EV_SPATIAL2DATLAS_DLL EV_DLL_EXPORT
#else
#define EV_SPATIAL2DATLAS_DLL EV_DLL_IMPORT
#endif

#endif
