#ifndef EARTHVIEW_WORLD_SPATIAL3D_ANALYSIS_COFING_H
#define EARTHVIEW_WORLD_SPATIAL3D_ANALYSIS_COFING_H
#include "core/global.h"
#ifdef EV_BUILD_ANALYSIS3D
#define EV_ANALYSIS3D_DLL EV_DLL_EXPORT
#else
#define EV_ANALYSIS3D_DLL EV_DLL_IMPORT
#endif

#endif
