#ifndef EARTHVIEW_WORLD_SPATIAL_EARTHVIEW_DOWNLOADEXPORTS_H
#define EARTHVIEW_WORLD_SPATIAL_EARTHVIEW_DOWNLOADEXPORTS_H
#include "core/global.h"
#include "core/ev_logger.h"

//动态库导出导入宏
#ifdef EV_BUILD_EARTHVIEW_DOWNLOAD
#define EV_EARTHVIEW_DOWNLOAD_DLL EV_DLL_EXPORT
#else
#define EV_EARTHVIEW_DOWNLOAD_DLL EV_DLL_IMPORT
#endif

#endif