#ifndef EARTHVIEW_WORLD_SPATIAL3D_CONTROLS_MAPCONTROLCONFIG_H
#define EARTHVIEW_WORLD_SPATIAL3D_CONTROLS_MAPCONTROLCONFIG_H
#include "core/core_api.h"


#ifdef EV_BUILD_MAPCONTROL
#define EV_MAPCONTROL_DLL EV_DLL_EXPORT
#else
#define EV_MAPCONTROL_DLL EV_DLL_IMPORT
#endif

#endif