#ifndef EARTHVIEW_WORLD_LAYOUT_CONTROLS_MAPCONTROLCONFIG_H
#define EARTHVIEW_WORLD_LAYOUT_CONTROLS_MAPCONTROLCONFIG_H
#include "core/core_api.h"


#ifdef EV_BUILD_LAYOUTCONTROL
#define EV_LAYOUTCONTROL_DLL EV_DLL_EXPORT
#else
#define EV_LAYOUTCONTROL_DLL EV_DLL_IMPORT
#endif

#endif