using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

public static class EV_SpatialObject_ClassFactory
{
	public static void RegisterAll()
	{
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CCoordinateSystemFactory", new EarthView.World.Spatial.Utility.CoordinateSystemFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CEllipseSpheriod", new EarthView.World.Spatial.Utility.EllipseSpheriodClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CEllipseSpheriodProxy", new EarthView.World.Spatial.Utility.EllipseSpheriodClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CProjParameter", new EarthView.World.Spatial.Utility.ProjParameterClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CTransParameter", new EarthView.World.Spatial.Utility.TransParameterClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CSpatialReference", new EarthView.World.Spatial.Utility.SpatialReferenceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CSpatialReferenceProxy", new EarthView.World.Spatial.Utility.SpatialReferenceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CGeoSpatialReference", new EarthView.World.Spatial.Utility.GeoSpatialReferenceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CGeoSpatialReferenceProxy", new EarthView.World.Spatial.Utility.GeoSpatialReferenceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CProjectedReference", new EarthView.World.Spatial.Utility.ProjectedReferenceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CProjectedReferenceProxy", new EarthView.World.Spatial.Utility.ProjectedReferenceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CCoordinateTransformation", new EarthView.World.Spatial.Utility.CoordinateTransformationClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CCoordinateTransformationProxy", new EarthView.World.Spatial.Utility.CoordinateTransformationClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CBezierCurve", new EarthView.World.Spatial.Geometry.BezierCurveClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CBezierCurveProxy", new EarthView.World.Spatial.Geometry.BezierCurveClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CBox", new EarthView.World.Spatial.Geometry.BoxClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CBoxProxy", new EarthView.World.Spatial.Geometry.BoxClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircle", new EarthView.World.Spatial.Geometry.CircleClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleProxy", new EarthView.World.Spatial.Geometry.CircleClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleArc", new EarthView.World.Spatial.Geometry.CircleArcClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleArcProxy", new EarthView.World.Spatial.Geometry.CircleArcClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleArcRing", new EarthView.World.Spatial.Geometry.CircleArcRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleArcRingProxy", new EarthView.World.Spatial.Geometry.CircleArcRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleChord", new EarthView.World.Spatial.Geometry.CircleChordClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleChordProxy", new EarthView.World.Spatial.Geometry.CircleChordClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleChordRing", new EarthView.World.Spatial.Geometry.CircleChordRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleChordRingProxy", new EarthView.World.Spatial.Geometry.CircleChordRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleRing", new EarthView.World.Spatial.Geometry.CircleRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleRingProxy", new EarthView.World.Spatial.Geometry.CircleRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleSector", new EarthView.World.Spatial.Geometry.CircleSectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleSectorProxy", new EarthView.World.Spatial.Geometry.CircleSectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleSectorRing", new EarthView.World.Spatial.Geometry.CircleSectorRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCircleSectorRingProxy", new EarthView.World.Spatial.Geometry.CircleSectorRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CColumn", new EarthView.World.Spatial.Geometry.ColumnClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CColumnProxy", new EarthView.World.Spatial.Geometry.ColumnClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCone", new EarthView.World.Spatial.Geometry.ConeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CConeProxy", new EarthView.World.Spatial.Geometry.ConeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCoordinate", new EarthView.World.Spatial.Geometry.CoordinateClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCoordinateProxy", new EarthView.World.Spatial.Geometry.CoordinateClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCoordinateSequence", new EarthView.World.Spatial.Geometry.CoordinateSequenceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCurve", new EarthView.World.Spatial.Geometry.CurveClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCurveProxy", new EarthView.World.Spatial.Geometry.CurveClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCurvePath", new EarthView.World.Spatial.Geometry.CurvePathClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCurvePathProxy", new EarthView.World.Spatial.Geometry.CurvePathClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCurveRing", new EarthView.World.Spatial.Geometry.CurveRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CCurveRingProxy", new EarthView.World.Spatial.Geometry.CurveRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipse", new EarthView.World.Spatial.Geometry.EllipseClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipseProxy", new EarthView.World.Spatial.Geometry.EllipseClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipsoid", new EarthView.World.Spatial.Geometry.EllipsoidClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipsoidProxy", new EarthView.World.Spatial.Geometry.EllipsoidClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticArc", new EarthView.World.Spatial.Geometry.EllipticArcClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticArcProxy", new EarthView.World.Spatial.Geometry.EllipticArcClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticArcRing", new EarthView.World.Spatial.Geometry.EllipticArcRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticArcRingProxy", new EarthView.World.Spatial.Geometry.EllipticArcRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticChord", new EarthView.World.Spatial.Geometry.EllipticChordClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticChordProxy", new EarthView.World.Spatial.Geometry.EllipticChordClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticChordRing", new EarthView.World.Spatial.Geometry.EllipticChordRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticChordRingProxy", new EarthView.World.Spatial.Geometry.EllipticChordRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticRing", new EarthView.World.Spatial.Geometry.EllipticRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticRingProxy", new EarthView.World.Spatial.Geometry.EllipticRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticSector", new EarthView.World.Spatial.Geometry.EllipticSectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticSectorProxy", new EarthView.World.Spatial.Geometry.EllipticSectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticSectorRing", new EarthView.World.Spatial.Geometry.EllipticSectorRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEllipticSectorRingProxy", new EarthView.World.Spatial.Geometry.EllipticSectorRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEnvelope", new EarthView.World.Spatial.Geometry.EnvelopeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CEnvelopeProxy", new EarthView.World.Spatial.Geometry.EnvelopeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CGeodesicMeasure", new EarthView.World.Spatial.Geometry.GeodesicMeasureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CGeodesicMeasureProxy", new EarthView.World.Spatial.Geometry.GeodesicMeasureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Utility::CGeodeticTheme", new EarthView.World.Spatial.Utility.GeodeticThemeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CGeometry", new EarthView.World.Spatial.Geometry.GeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CGeometryProxy", new EarthView.World.Spatial.Geometry.GeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CGeometryCollection", new EarthView.World.Spatial.Geometry.GeometryCollectionClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CGeometryCollectionProxy", new EarthView.World.Spatial.Geometry.GeometryCollectionClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CGeometryFactory", new EarthView.World.Spatial.Geometry.GeometryFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CLine", new EarthView.World.Spatial.Geometry.LineClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CLineProxy", new EarthView.World.Spatial.Geometry.LineClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CLineString", new EarthView.World.Spatial.Geometry.LineStringClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CLineStringProxy", new EarthView.World.Spatial.Geometry.LineStringClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CMultiPoint", new EarthView.World.Spatial.Geometry.MultiPointClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CMultiPointProxy", new EarthView.World.Spatial.Geometry.MultiPointClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CPoint", new EarthView.World.Spatial.Geometry.PointClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CPointProxy", new EarthView.World.Spatial.Geometry.PointClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CPolygon", new EarthView.World.Spatial.Geometry.PolygonClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CPolygonProxy", new EarthView.World.Spatial.Geometry.PolygonClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CPolyline", new EarthView.World.Spatial.Geometry.PolylineClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CPolylineProxy", new EarthView.World.Spatial.Geometry.PolylineClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRectangle", new EarthView.World.Spatial.Geometry.RectangleClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRectangleProxy", new EarthView.World.Spatial.Geometry.RectangleClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRectangleRing", new EarthView.World.Spatial.Geometry.RectangleRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRectangleRingProxy", new EarthView.World.Spatial.Geometry.RectangleRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRevolvingVolume", new EarthView.World.Spatial.Geometry.RevolvingVolumeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRevolvingVolumeProxy", new EarthView.World.Spatial.Geometry.RevolvingVolumeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRing", new EarthView.World.Spatial.Geometry.RingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRingProxy", new EarthView.World.Spatial.Geometry.RingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CRotatedEnvelope", new EarthView.World.Spatial.Geometry.RotatedEnvelopeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CSphereGeometryFactory", new EarthView.World.Spatial.Geometry.SphereGeometryFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CSurface", new EarthView.World.Spatial.Geometry.SurfaceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CSurfaceProxy", new EarthView.World.Spatial.Geometry.SurfaceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangle", new EarthView.World.Spatial.Geometry.TriangleClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangleProxy", new EarthView.World.Spatial.Geometry.TriangleClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangleFan", new EarthView.World.Spatial.Geometry.TriangleFanClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangleFanProxy", new EarthView.World.Spatial.Geometry.TriangleFanClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangleRing", new EarthView.World.Spatial.Geometry.TriangleRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangleRingProxy", new EarthView.World.Spatial.Geometry.TriangleRingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangleStrip", new EarthView.World.Spatial.Geometry.TriangleStripClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CTriangleStripProxy", new EarthView.World.Spatial.Geometry.TriangleStripClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CVolume", new EarthView.World.Spatial.Geometry.VolumeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Geometry::CVolumeProxy", new EarthView.World.Spatial.Geometry.VolumeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::GeoIndex", new EarthView.World.Spatial.GeoIndexClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::CGeoObject", new EarthView.World.Spatial.GeoObjectClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::CGeoObject::CLookAt", new EarthView.World.Spatial.GeoObject.LookAtClassFactory());
	}
}

