#ifndef EARTHVIEW_WORLD_SPATIAL3D_STREETVIEW_COFING_H
#define EARTHVIEW_WORLD_SPATIAL3D_STREETVIEW_COFING_H

#include "core/global.h"

#ifdef EV_BUILD_SPATIAL3DESTREETVIEW
#define EV_Spatial3DStreetView_DLL EV_DLL_EXPORT
#else
#define EV_Spatial3DStreetView_DLL EV_DLL_IMPORT
#endif

#endif