using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

public static class EV_RTShaderSystem_ClassFactory
{
	public static void RegisterAll()
	{
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CCGProgramProcessor", new EarthView.World.Graphic.Rtshadersystem.CgprogramprocessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CCGProgramProcessorProxy", new EarthView.World.Graphic.Rtshadersystem.CgprogramprocessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CDualQuaternionSkinning", new EarthView.World.Graphic.Rtshadersystem.DualQuaternionSkinningClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CDualQuaternionSkinningProxy", new EarthView.World.Graphic.Rtshadersystem.DualQuaternionSkinningClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHardwareSkinning", new EarthView.World.Graphic.Rtshadersystem.HardwareSkinningClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHardwareSkinningProxy", new EarthView.World.Graphic.Rtshadersystem.HardwareSkinningClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHardwareSkinning::SkinningData", new EarthView.World.Graphic.Rtshadersystem.HardwareSkinning.SkinningDataClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHardwareSkinningFactory", new EarthView.World.Graphic.Rtshadersystem.HardwareSkinningFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHardwareSkinningFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.HardwareSkinningFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHardwareSkinningTechnique", new EarthView.World.Graphic.Rtshadersystem.HardwareSkinningTechniqueClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHardwareSkinningTechniqueProxy", new EarthView.World.Graphic.Rtshadersystem.HardwareSkinningTechniqueClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CIntegratedPSSM3", new EarthView.World.Graphic.Rtshadersystem.IntegratedPSSM3ClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CIntegratedPSSM3Proxy", new EarthView.World.Graphic.Rtshadersystem.IntegratedPSSM3ClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CIntegratedPSSM3::Integratedppssm3SplitPointList", new EarthView.World.Graphic.Rtshadersystem.IntegratedPSSM3.Integratedppssm3SplitPointListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CIntegratedPSSM3Factory", new EarthView.World.Graphic.Rtshadersystem.IntegratedPSSM3FactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CIntegratedPSSM3FactoryProxy", new EarthView.World.Graphic.Rtshadersystem.IntegratedPSSM3FactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CLayeredBlending", new EarthView.World.Graphic.Rtshadersystem.LayeredBlendingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CLayeredBlendingProxy", new EarthView.World.Graphic.Rtshadersystem.LayeredBlendingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CLayeredBlending::TextureBlend", new EarthView.World.Graphic.Rtshadersystem.LayeredBlending.TextureBlendClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CLinearSkinning", new EarthView.World.Graphic.Rtshadersystem.LinearSkinningClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CLinearSkinningProxy", new EarthView.World.Graphic.Rtshadersystem.LinearSkinningClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CNormalMapLighting", new EarthView.World.Graphic.Rtshadersystem.NormalMapLightingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CNormalMapLightingProxy", new EarthView.World.Graphic.Rtshadersystem.NormalMapLightingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CNormalMapLightingFactory", new EarthView.World.Graphic.Rtshadersystem.NormalMapLightingFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CNormalMapLightingFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.NormalMapLightingFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CPerPixelLighting", new EarthView.World.Graphic.Rtshadersystem.PerPixelLightingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CPerPixelLightingProxy", new EarthView.World.Graphic.Rtshadersystem.PerPixelLightingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CPerPixelLightingFactory", new EarthView.World.Graphic.Rtshadersystem.PerPixelLightingFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CPerPixelLightingFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.PerPixelLightingFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::TextureAtlasRecord", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasRecordClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::TextureAtlasTable", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasTableClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::TextureAtlasTablePtr", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasTablePtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::TextureAtlasMap", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasMapClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CTextureAtlasSampler", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasSamplerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CTextureAtlasSamplerProxy", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasSamplerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CTextureAtlasSamplerFactory", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasSamplerFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CTextureAtlasSamplerFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasSamplerFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CTextureAtlasSamplerFactory::TextureAtlasAttib", new EarthView.World.Graphic.Rtshadersystem.TextureAtlasSamplerFactory.TextureAtlasAttibClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPColour", new EarthView.World.Graphic.Rtshadersystem.FfpcolourClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPColourProxy", new EarthView.World.Graphic.Rtshadersystem.FfpcolourClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPColourFactory", new EarthView.World.Graphic.Rtshadersystem.FfpcolourfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPColourFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.FfpcolourfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPFog", new EarthView.World.Graphic.Rtshadersystem.FfpfogClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPFogProxy", new EarthView.World.Graphic.Rtshadersystem.FfpfogClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPFogFactory", new EarthView.World.Graphic.Rtshadersystem.FfpfogfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPFogFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.FfpfogfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPLighting", new EarthView.World.Graphic.Rtshadersystem.FfplightingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPLightingProxy", new EarthView.World.Graphic.Rtshadersystem.FfplightingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPLightingFactory", new EarthView.World.Graphic.Rtshadersystem.FfplightingfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPLightingFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.FfplightingfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPRenderStateBuilder", new EarthView.World.Graphic.Rtshadersystem.FfprenderstatebuilderClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTexturing", new EarthView.World.Graphic.Rtshadersystem.FfptexturingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTexturingProxy", new EarthView.World.Graphic.Rtshadersystem.FfptexturingClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTexturing::TextureUnitParams", new EarthView.World.Graphic.Rtshadersystem.Ffptexturing.TextureUnitParamsClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTexturingFactory", new EarthView.World.Graphic.Rtshadersystem.FfptexturingfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTexturingFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.FfptexturingfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTransform", new EarthView.World.Graphic.Rtshadersystem.FfptransformClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTransformProxy", new EarthView.World.Graphic.Rtshadersystem.FfptransformClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTransformFactory", new EarthView.World.Graphic.Rtshadersystem.FfptransformfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFFPTransformFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.FfptransformfactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFunction", new EarthView.World.Graphic.Rtshadersystem.FunctionClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::ShaderFunctionList", new EarthView.World.Graphic.Rtshadersystem.ShaderFunctionListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFunctionAtom", new EarthView.World.Graphic.Rtshadersystem.FunctionAtomClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFunctionAtomProxy", new EarthView.World.Graphic.Rtshadersystem.FunctionAtomClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::COperand", new EarthView.World.Graphic.Rtshadersystem.OperandClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFunctionInvocation", new EarthView.World.Graphic.Rtshadersystem.FunctionInvocationClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFunctionInvocationProxy", new EarthView.World.Graphic.Rtshadersystem.FunctionInvocationClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CFunctionInvocation::OperandVector", new EarthView.World.Graphic.Rtshadersystem.FunctionInvocation.OperandVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::FunctionAtomInstanceList", new EarthView.World.Graphic.Rtshadersystem.FunctionAtomInstanceListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator", new EarthView.World.Graphic.Rtshadersystem.ShaderGeneratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::RenderStateCreateOrRetrieveResult", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.RenderStateCreateOrRetrieveResultClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGTechniqueList", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgtechniquelistClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGPass", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgpassClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGTechnique", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgtechniqueClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGMaterial", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgmaterialClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGScheme", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgschemeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGRenderObjectListener", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgrenderobjectlistenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGRenderObjectListenerProxy", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgrenderobjectlistenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGSceneManagerListener", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgscenemanagerlistenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGSceneManagerListenerProxy", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgscenemanagerlistenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGScriptTranslatorManager", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgscripttranslatormanagerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CShaderGenerator::SGScriptTranslatorManagerProxy", new EarthView.World.Graphic.Rtshadersystem.ShaderGenerator.SgscripttranslatormanagerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CGLSLProgramProcessor", new EarthView.World.Graphic.Rtshadersystem.GlslprogramprocessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CGLSLProgramProcessorProxy", new EarthView.World.Graphic.Rtshadersystem.GlslprogramprocessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHLSLProgramProcessor", new EarthView.World.Graphic.Rtshadersystem.HlslprogramprocessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CHLSLProgramProcessorProxy", new EarthView.World.Graphic.Rtshadersystem.HlslprogramprocessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSGMaterialSerializerListener", new EarthView.World.Graphic.Rtshadersystem.SgmaterialserializerlistenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSGMaterialSerializerListenerProxy", new EarthView.World.Graphic.Rtshadersystem.SgmaterialserializerlistenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CParameter", new EarthView.World.Graphic.Rtshadersystem.ParameterClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CParameterProxy", new EarthView.World.Graphic.Rtshadersystem.ParameterClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::ParameterPtr", new EarthView.World.Graphic.Rtshadersystem.ParameterPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::ShaderParameterList", new EarthView.World.Graphic.Rtshadersystem.ShaderParameterListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CUniformParameter", new EarthView.World.Graphic.Rtshadersystem.UniformParameterClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CUniformParameterProxy", new EarthView.World.Graphic.Rtshadersystem.UniformParameterClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::UniformParameterPtr", new EarthView.World.Graphic.Rtshadersystem.UniformParameterPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::UniformParameterList", new EarthView.World.Graphic.Rtshadersystem.UniformParameterListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CParameterFactory", new EarthView.World.Graphic.Rtshadersystem.ParameterFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CProgram", new EarthView.World.Graphic.Rtshadersystem.ProgramClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CProgramProcessor", new EarthView.World.Graphic.Rtshadersystem.ProgramProcessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CProgramProcessorProxy", new EarthView.World.Graphic.Rtshadersystem.ProgramProcessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CProgramSet", new EarthView.World.Graphic.Rtshadersystem.ProgramSetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CRenderState", new EarthView.World.Graphic.Rtshadersystem.RenderStateClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::RenderStateList", new EarthView.World.Graphic.Rtshadersystem.RenderStateListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CTargetRenderState", new EarthView.World.Graphic.Rtshadersystem.TargetRenderStateClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSGScriptTranslator", new EarthView.World.Graphic.Rtshadersystem.SgscripttranslatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSGScriptTranslatorProxy", new EarthView.World.Graphic.Rtshadersystem.SgscripttranslatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::SubRenderStateAccessorPtr", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateAccessorPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSubRenderState", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSubRenderStateProxy", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::SubRenderStateList", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::SubRenderStateSet", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateSetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSubRenderStateAccessor", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateAccessorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSubRenderStateFactory", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Graphic::RTShaderSystem::CSubRenderStateFactoryProxy", new EarthView.World.Graphic.Rtshadersystem.SubRenderStateFactoryClassFactory());
	}
}

