#ifndef EARTHVIEW_WORLD_SPATIAL_SYSTEMUI_EVCHARTENTRYBOX_API_H
#define EARTHVIEW_WORLD_SPATIAL_SYSTEMUI_EVCHARTENTRYBOX_API_H

#ifdef EV_CHARTENTRYBOX_EXPORTS
	#define EVCHARTENTRYBOX_API EV_DLL_EXPORT
#else
	#define EVCHARTENTRYBOX_API EV_DLL_IMPORT
#endif

#include "core/core_api.h"
#endif
