#ifndef EARTHVIEW_WORLD_SPATIAL2D_GEODATABASE_COFING_H
#define EARTHVIEW_WORLD_SPATIAL2D_GEODATABASE_COFING_H


#include "core/global.h"

#ifdef EV_SPATIAL2DGEODATABASE_EXPORTS
#define EV_2DGEODATABSE_DLL EV_DLL_EXPORT
#else
#define EV_2DGEODATABSE_DLL EV_DLL_IMPORT
#endif

//#define EV_USE_CORE

//#ifdef EV_USE_CORE
#include "core/core_api.h"
//#endif


#endif 