using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

public static class EV_GA_ClassFactory
{
	public static void RegisterAll()
	{
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRoamCameraEvent", new EarthView.World.Spatial3D.Controls.RoamCameraEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRoamCameraEventPtr", new EarthView.World.Spatial3D.Controls.RoamCameraEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CZoomCameraEvent", new EarthView.World.Spatial3D.Controls.ZoomCameraEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CZoomCameraEventPtr", new EarthView.World.Spatial3D.Controls.ZoomCameraEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRotationCameraEvent", new EarthView.World.Spatial3D.Controls.RotationCameraEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRotationCameraEventPtr", new EarthView.World.Spatial3D.Controls.RotationCameraEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CTiltCameraEventEX", new EarthView.World.Spatial3D.Controls.TiltCameraEventEXClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CTiltCameraEventEXPtr", new EarthView.World.Spatial3D.Controls.TiltCameraEventEXPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraRotationratioEventEX", new EarthView.World.Spatial3D.Controls.SetCameraRotationratioEventEXClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraRotationratioEventEXPtr", new EarthView.World.Spatial3D.Controls.SetCameraRotationratioEventEXPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCameraManipulator", new EarthView.World.Spatial3D.Controls.CameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCameraManipulatorProxy", new EarthView.World.Spatial3D.Controls.CameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCameraNodeTrackSceneManagerListener", new EarthView.World.Spatial3D.Controls.CameraNodeTrackSceneManagerListenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCameraNodeTrackSceneManagerListenerProxy", new EarthView.World.Spatial3D.Controls.CameraNodeTrackSceneManagerListenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCollisionDetectionCameraManipulator", new EarthView.World.Spatial3D.Controls.CollisionDetectionCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCollisionDetectionCameraManipulatorProxy", new EarthView.World.Spatial3D.Controls.CollisionDetectionCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRecordEvent", new EarthView.World.Spatial3D.Controls.RecordEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CControlPointEvent", new EarthView.World.Spatial3D.Controls.ControlPointEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommonSceneCameraManipulator", new EarthView.World.Spatial3D.Controls.CommonSceneCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CCommonSceneCameraManipulatorProxy", new EarthView.World.Spatial3D.Controls.CommonSceneCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CPointEditRenderable", new EarthView.World.Spatial3D.Controls.PointEditRenderableClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CPointEditRenderableProxy", new EarthView.World.Spatial3D.Controls.PointEditRenderableClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CPointEdit", new EarthView.World.Spatial3D.Controls.PointEditClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CPointEditList", new EarthView.World.Spatial3D.Controls.PointEditListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRouteFlyListener", new EarthView.World.Spatial3D.Controls.RouteFlyListenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRouteFlyListenerProxy", new EarthView.World.Spatial3D.Controls.RouteFlyListenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CControlPoints", new EarthView.World.Spatial3D.Controls.ControlPointsClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeAnimationHandler", new EarthView.World.Spatial3D.Controls.GlobeAnimationHandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeAnimationHandlerProxy", new EarthView.World.Spatial3D.Controls.GlobeAnimationHandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeAnimationControlPoint", new EarthView.World.Spatial3D.Controls.GlobeAnimationControlPointClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CAnimationControlPointMap", new EarthView.World.Spatial3D.Controls.AnimationControlPointMapClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeAnimationPath", new EarthView.World.Spatial3D.Controls.GlobeAnimationPathClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGoToTargetListener", new EarthView.World.Spatial3D.Controls.GoToTargetListenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGoToTargetListenerProxy", new EarthView.World.Spatial3D.Controls.GoToTargetListenerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeCameraManipulator", new EarthView.World.Spatial3D.Controls.GlobeCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeCameraManipulatorProxy", new EarthView.World.Spatial3D.Controls.GlobeCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeCamUnderGroundHandler", new EarthView.World.Spatial3D.Controls.GlobeCamUnderGroundHandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeCamUnderGroundHandlerProxy", new EarthView.World.Spatial3D.Controls.GlobeCamUnderGroundHandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyDataEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyDataEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyDataEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyDataEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyPlayEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyPlayEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyPlayEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyPlayEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyPauseEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyPauseEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyPauseEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyPauseEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyStopEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyStopEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyStopEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyStopEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyStartSamplePointEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyStartSamplePointEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyStartSamplePointEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyStartSamplePointEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyStopSamplePointEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyStopSamplePointEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyStopSamplePointEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyStopSamplePointEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyShowAxisEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyShowAxisEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyShowAxisEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyShowAxisEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyAdjustModeEvent", new EarthView.World.Spatial3D.Controls.GlobeFlyAdjustModeEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeFlyAdjustModeEventPtr", new EarthView.World.Spatial3D.Controls.GlobeFlyAdjustModeEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeLockCameraHandler", new EarthView.World.Spatial3D.Controls.GlobeLockCameraHandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGlobeLockCameraHandlerProxy", new EarthView.World.Spatial3D.Controls.GlobeLockCameraHandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGoogleCameraManipulator", new EarthView.World.Spatial3D.Controls.GoogleCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGoogleCameraManipulatorProxy", new EarthView.World.Spatial3D.Controls.GoogleCameraManipulatorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGotoEvent", new EarthView.World.Spatial3D.Controls.GotoEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGotoEventPtr", new EarthView.World.Spatial3D.Controls.GotoEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CLocationEvent", new EarthView.World.Spatial3D.Controls.LocationEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CLocationEventPtr", new EarthView.World.Spatial3D.Controls.LocationEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraControlDepthEvent", new EarthView.World.Spatial3D.Controls.SetCameraControlDepthEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraControlDepthEventPtr", new EarthView.World.Spatial3D.Controls.SetCameraControlDepthEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRotationAndZoomCameraEvent", new EarthView.World.Spatial3D.Controls.RotationAndZoomCameraEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CRotationAndZoomCameraEventPtr", new EarthView.World.Spatial3D.Controls.RotationAndZoomCameraEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CTiltCameraEvent", new EarthView.World.Spatial3D.Controls.TiltCameraEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CTiltCameraEventPtr", new EarthView.World.Spatial3D.Controls.TiltCameraEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraRotationratioEvent", new EarthView.World.Spatial3D.Controls.SetCameraRotationratioEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraRotationratioEventPtr", new EarthView.World.Spatial3D.Controls.SetCameraRotationratioEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraLockTargetEvent", new EarthView.World.Spatial3D.Controls.SetCameraLockTargetEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CSetCameraLockTargetEventPtr", new EarthView.World.Spatial3D.Controls.SetCameraLockTargetEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CFadeInOutEvent", new EarthView.World.Spatial3D.Controls.FadeInOutEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CFadeInOutEventPtr", new EarthView.World.Spatial3D.Controls.FadeInOutEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGUIEventHandler", new EarthView.World.Spatial3D.Controls.GuieventhandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGUIEventHandlerProxy", new EarthView.World.Spatial3D.Controls.GuieventhandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CEvents", new EarthView.World.Spatial3D.Controls.EventsClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CGUIEventQueue", new EarthView.World.Spatial3D.Controls.GuieventqueueClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CTourEndEvent", new EarthView.World.Spatial3D.Controls.TourEndEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlTourEvent", new EarthView.World.Spatial3D.Controls.KmlTourEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlTourEventPtr", new EarthView.World.Spatial3D.Controls.KmlTourEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlTourPathEvent", new EarthView.World.Spatial3D.Controls.KmlTourPathEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlTourPathEventPtr", new EarthView.World.Spatial3D.Controls.KmlTourPathEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStartTourEvent", new EarthView.World.Spatial3D.Controls.KmlStartTourEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStartTourEventPtr", new EarthView.World.Spatial3D.Controls.KmlStartTourEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStopTourEvent", new EarthView.World.Spatial3D.Controls.KmlStopTourEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStopTourEventPtr", new EarthView.World.Spatial3D.Controls.KmlStopTourEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStartRecordTourEvent", new EarthView.World.Spatial3D.Controls.KmlStartRecordTourEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStartRecordTourEventPtr", new EarthView.World.Spatial3D.Controls.KmlStartRecordTourEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStopRecordTourEvent", new EarthView.World.Spatial3D.Controls.KmlStopRecordTourEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlStopRecordTourEventPtr", new EarthView.World.Spatial3D.Controls.KmlStopRecordTourEventPtrClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlTourHandler", new EarthView.World.Spatial3D.Controls.KmlTourHandlerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Controls::CKmlTourHandlerProxy", new EarthView.World.Spatial3D.Controls.KmlTourHandlerClassFactory());
	}
}

