using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

public static class EV_Spatial3DDataset_ClassFactory
{
	public static void RegisterAll()
	{
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSetIterator", new EarthView.World.Spatial3D.Dataset.EffectDataSetIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSetIteratorProxy", new EarthView.World.Spatial3D.Dataset.EffectDataSetIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSet", new EarthView.World.Spatial3D.Dataset.EffectDataSetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSetProxy", new EarthView.World.Spatial3D.Dataset.EffectDataSetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectGeometryField", new EarthView.World.Spatial3D.Dataset.EffectGeometryFieldClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectGeometryFieldProxy", new EarthView.World.Spatial3D.Dataset.EffectGeometryFieldClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSource", new EarthView.World.Spatial3D.Dataset.EffectDataSourceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSourceProxy", new EarthView.World.Spatial3D.Dataset.EffectDataSourceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSourceFactory", new EarthView.World.Spatial3D.Dataset.EffectDataSourceFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectDataSourceFactoryProxy", new EarthView.World.Spatial3D.Dataset.EffectDataSourceFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectFeature", new EarthView.World.Spatial3D.Dataset.EffectFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectFeatureProxy", new EarthView.World.Spatial3D.Dataset.EffectFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectFeatureIterator", new EarthView.World.Spatial3D.Dataset.EffectFeatureIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectFeatureIteratorProxy", new EarthView.World.Spatial3D.Dataset.EffectFeatureIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectInstance", new EarthView.World.Spatial3D.Dataset.EffectInstanceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectInstanceVector", new EarthView.World.Spatial3D.Dataset.EffectInstanceVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectUserTypeInfo", new EarthView.World.Spatial3D.Dataset.EffectUserTypeInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectUserTypeInfoVector", new EarthView.World.Spatial3D.Dataset.EffectUserTypeInfoVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectRefInfo", new EarthView.World.Spatial3D.Dataset.EffectRefInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectRefInfoVector", new EarthView.World.Spatial3D.Dataset.EffectRefInfoVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectResourceInfo", new EarthView.World.Spatial3D.Dataset.EffectResourceInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectResourceInfoVector", new EarthView.World.Spatial3D.Dataset.EffectResourceInfoVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectFeatureVector", new EarthView.World.Spatial3D.Dataset.EffectFeatureVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectUserTypeTree", new EarthView.World.Spatial3D.Dataset.EffectUserTypeTreeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityDataset", new EarthView.World.Spatial3D.Dataset.EntityDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityDatasetProxy", new EarthView.World.Spatial3D.Dataset.EntityDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::ModelEditOperation", new EarthView.World.Spatial3D.Dataset.ModelEditOperationClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityDatasetIterator", new EarthView.World.Spatial3D.Dataset.EntityDatasetIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityDatasetIteratorProxy", new EarthView.World.Spatial3D.Dataset.EntityDatasetIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityFeature", new EarthView.World.Spatial3D.Dataset.EntityFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityFeatureProxy", new EarthView.World.Spatial3D.Dataset.EntityFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityGeometry", new EarthView.World.Spatial3D.Dataset.EntityGeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityGeometryProxy", new EarthView.World.Spatial3D.Dataset.EntityGeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityGeometryFactory", new EarthView.World.Spatial3D.Dataset.EntityGeometryFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityIterator", new EarthView.World.Spatial3D.Dataset.EntityIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntityIteratorProxy", new EarthView.World.Spatial3D.Dataset.EntityIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntitySelection", new EarthView.World.Spatial3D.Dataset.EntitySelectionClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEntitySelectionProxy", new EarthView.World.Spatial3D.Dataset.EntitySelectionClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CFeatureSelection3D", new EarthView.World.Spatial3D.Dataset.FeatureSelection3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CFeatureSelection3DProxy", new EarthView.World.Spatial3D.Dataset.FeatureSelection3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshEffectRefInfo", new EarthView.World.Spatial3D.Dataset.MeshEffectRefInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshEffectRefInfoVector", new EarthView.World.Spatial3D.Dataset.MeshEffectRefInfoVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshEffectRefManager", new EarthView.World.Spatial3D.Dataset.MeshEffectRefManagerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateDataset", new EarthView.World.Spatial3D.Dataset.MeshTemplateDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateDatasetProxy", new EarthView.World.Spatial3D.Dataset.MeshTemplateDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateFeature", new EarthView.World.Spatial3D.Dataset.MeshTemplateFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateFeatureProxy", new EarthView.World.Spatial3D.Dataset.MeshTemplateFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateGeometry", new EarthView.World.Spatial3D.Dataset.MeshTemplateGeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateGeometryProxy", new EarthView.World.Spatial3D.Dataset.MeshTemplateGeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateGeometryFactory", new EarthView.World.Spatial3D.Dataset.MeshTemplateGeometryFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateIterator", new EarthView.World.Spatial3D.Dataset.MeshTemplateIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CMeshTemplateIteratorProxy", new EarthView.World.Spatial3D.Dataset.MeshTemplateIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelCacheUtility", new EarthView.World.Spatial3D.Dataset.ModelCacheUtilityClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDataset", new EarthView.World.Spatial3D.Dataset.ModelDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDatasetProxy", new EarthView.World.Spatial3D.Dataset.ModelDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDatasetEditEvent", new EarthView.World.Spatial3D.Dataset.ModelDatasetEditEventClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDatasetUtility", new EarthView.World.Spatial3D.Dataset.ModelDatasetUtilityClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelGeometryField", new EarthView.World.Spatial3D.Dataset.ModelGeometryFieldClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelGeometryFieldProxy", new EarthView.World.Spatial3D.Dataset.ModelGeometryFieldClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDataSource", new EarthView.World.Spatial3D.Dataset.ModelDataSourceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDataSourceProxy", new EarthView.World.Spatial3D.Dataset.ModelDataSourceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDataSourceFactory", new EarthView.World.Spatial3D.Dataset.ModelDataSourceFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelDataSourceFactoryProxy", new EarthView.World.Spatial3D.Dataset.ModelDataSourceFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelEventUtility", new EarthView.World.Spatial3D.Dataset.ModelEventUtilityClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelFeatureUtility", new EarthView.World.Spatial3D.Dataset.ModelFeatureUtilityClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CModelOctreeManager", new EarthView.World.Spatial3D.Dataset.ModelOctreeManagerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("CResourceData", new ResourceDataClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("CResourceDataList", new ResourceDataListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("CModelData", new ModelDataClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("IModelTemplatePlugin", new ImodeltemplatepluginClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("IModelTemplatePluginProxy", new ImodeltemplatepluginClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CObjectIDList", new EarthView.World.Spatial3D.Dataset.ObjectIDListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CPropertyManager", new EarthView.World.Spatial3D.Dataset.PropertyManagerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceDataset", new EarthView.World.Spatial3D.Dataset.ResourceDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceDatasetProxy", new EarthView.World.Spatial3D.Dataset.ResourceDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceFeature", new EarthView.World.Spatial3D.Dataset.ResourceFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceFeatureProxy", new EarthView.World.Spatial3D.Dataset.ResourceFeatureClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceGeometry", new EarthView.World.Spatial3D.Dataset.ResourceGeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceGeometryProxy", new EarthView.World.Spatial3D.Dataset.ResourceGeometryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceGeometryFactory", new EarthView.World.Spatial3D.Dataset.ResourceGeometryFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceIterator", new EarthView.World.Spatial3D.Dataset.ResourceIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CResourceIteratorProxy", new EarthView.World.Spatial3D.Dataset.ResourceIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::TextureStreamItem", new EarthView.World.Spatial3D.Dataset.TextureStreamItemClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::TextureStreamVector", new EarthView.World.Spatial3D.Dataset.TextureStreamVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::FeatureVector", new EarthView.World.Spatial3D.Dataset.FeatureVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::IntMap", new EarthView.World.Spatial3D.Dataset.IntMapClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectInfo", new EarthView.World.Spatial3D.Dataset.EffectInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CEffectInfoVector", new EarthView.World.Spatial3D.Dataset.EffectInfoVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::DataSetVector", new EarthView.World.Spatial3D.Dataset.DataSetVectorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CUserTypeInfo", new EarthView.World.Spatial3D.Dataset.UserTypeInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CUserTypeTree", new EarthView.World.Spatial3D.Dataset.UserTypeTreeClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CUserTypeInfoList", new EarthView.World.Spatial3D.Dataset.UserTypeInfoListClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::NodecodeAndTypeMap", new EarthView.World.Spatial3D.Dataset.NodecodeAndTypeMapClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CUserTypeManager", new EarthView.World.Spatial3D.Dataset.UserTypeManagerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDataset", new EarthView.World.Spatial3D.Dataset.VectorOctreeDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDatasetProxy", new EarthView.World.Spatial3D.Dataset.VectorOctreeDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDataSource", new EarthView.World.Spatial3D.Dataset.VectorOctreeDataSourceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDataSourceProxy", new EarthView.World.Spatial3D.Dataset.VectorOctreeDataSourceClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDataSourceFactory", new EarthView.World.Spatial3D.Dataset.VectorOctreeDataSourceFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDataSourceFactoryProxy", new EarthView.World.Spatial3D.Dataset.VectorOctreeDataSourceFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDataMetaInfo", new EarthView.World.Spatial3D.Dataset.VectorOctreeDataMetaInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CVectorOctreeDataMetaInfoProxy", new EarthView.World.Spatial3D.Dataset.VectorOctreeDataMetaInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CWebEntityDataset", new EarthView.World.Spatial3D.Dataset.WebEntityDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CWebEntityDatasetProxy", new EarthView.World.Spatial3D.Dataset.WebEntityDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CWebEntityIterator", new EarthView.World.Spatial3D.Dataset.WebEntityIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CWebEntityIteratorProxy", new EarthView.World.Spatial3D.Dataset.WebEntityIteratorClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CWebMeshTemplateDataset", new EarthView.World.Spatial3D.Dataset.WebMeshTemplateDatasetClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial3D::Dataset::CWebMeshTemplateDatasetProxy", new EarthView.World.Spatial3D.Dataset.WebMeshTemplateDatasetClassFactory());
	}
}

