#ifndef EARTHVIEW_WORLD_SPATIAL_NETWORK_ANALYSIS_CONFIG_H
#define EARTHVIEW_WORLD_SPATIAL_NETWORK_ANALYSIS_CONFIG_H
#include "core/core_api.h"

#ifdef EV_NETWORKANALYSIS_EXPORTS
#define EV_NETWORKANALYSIS_DLL EV_DLL_EXPORT
#else
#define EV_NETWORKANALYSIS_DLL EV_DLL_IMPORT
#endif

#endif
