#ifndef _ShaderScriptTranslator_
#define _ShaderScriptTranslator_
#include "shaderprerequisites.h"
#include "graphic/scripttranslator.h"
#include "graphic/scriptcompiler.h"

namespace EarthView
{
    namespace World
    {
        namespace Graphic
        {
            namespace RTShaderSystem
            {

                class EV_RTSS_DLL CSGScriptTranslator : public EarthView::World::Graphic::CScriptTranslator
				{
			ev_private:
					CSGScriptTranslator(_in EarthView::World::Core::CNameValuePairList* pList);
				public:

					CSGScriptTranslator();

					/**
					*@see CScriptTranslator::translate.
					*/
					virtual void translate(EarthView::World::Graphic::CScriptCompiler *compiler, _in  const EarthView::World::Graphic::AbstractNodePtr &node);

					/**
					*@see CScriptTranslator::getBoolean.
					*/
					using EarthView::World::Graphic::CScriptTranslator::getBoolean;

					/**
					*@see CScriptTranslator::getBoolean.
					*/
					using EarthView::World::Graphic::CScriptTranslator::getString;

					/**
					*@see CScriptTranslator::getReal.
					*/
					using EarthView::World::Graphic::CScriptTranslator::getReal;

					/**
					*@see CScriptTranslator::getFloat.
					*/
					using EarthView::World::Graphic::CScriptTranslator::getFloat;

					/**
					*@see CScriptTranslator::getInt.
					*/
					using EarthView::World::Graphic::CScriptTranslator::getInt; 

					/**
					*@see CScriptTranslator::getUInt.
					*/
					using EarthView::World::Graphic::CScriptTranslator::getUInt; 

					/**
					*@see CScriptTranslator::getColour.
					*/
					using EarthView::World::Graphic::CScriptTranslator::getColour;

					/**
					* Returns a sub render state of a given name which has already 
					* been created for material currently being generated by the 
					* script translator
					* @note
					* This function is meant to be used from within the createInstance 
					* function of sub-render state factories to avoid creating multiple
					* sub-render state to the same material.
					*
					* @param typeName The type of the sub-render state to find.
					*/
					virtual EarthView::World::Graphic::RTShaderSystem::CSubRenderState* getGeneratedSubRenderState(const EVString& typeName);

					virtual CScriptTranslator *clone(){return new CSGScriptTranslator();}

				protected:
					/**
					* Translates RT Shader System section within a pass context.
					* @param compiler The compiler invoking this translator
					* @param node The current AST node to be translated
					*/
					void translatePass(EarthView::World::Graphic::CScriptCompiler *compiler, const EarthView::World::Graphic::AbstractNodePtr &node);

					/**
					* Translates RT Shader System section within a texture_unit context.
					* @param compiler The compiler invoking this translator
					* @param node The current AST node to be translated
					*/
					void translateTextureUnit(EarthView::World::Graphic::CScriptCompiler *compiler, const EarthView::World::Graphic::AbstractNodePtr &node);

					/**
					* Adds a newly created subrender state to the material being translated
					* @param newSubRenderState The sub-render state to add
					* @param dstTechniqueSchemeName The technique which the sub render state is associated with
					* @param materialName The material name which the sub render state is associated with
					* @param groupName The material group name which the sub render state is associated with
					* @param passIndex The index of the pass which the sub render state is associated with
					*/
					void addSubRenderState(EarthView::World::Graphic::RTShaderSystem::CSubRenderState* newSubRenderState, 
						const EVString& dstTechniqueSchemeName, const EVString& materialName, 
						const EVString& groupName, ev_uint16 passIndex);


				protected:

					EarthView::World::Graphic::RTShaderSystem::CRenderState* mGeneratedRenderState; //Render state created as a result of the current node being parsed

				};
            }

        }
    }
}
#endif

