#ifndef EARTHVIEW_WORLD_SPATIAL_GEODATASET_H
#define EARTHVIEW_WORLD_SPATIAL_GEODATASET_H

#ifdef EV_BULID_SPATIALDATABASE
#define EV_SPATIALDATABASE_DLL EV_DLL_EXPORT
#else
#define EV_SPATIALDATABASE_DLL EV_DLL_IMPORT
#endif

#include "core/core_api.h"

#endif
