#ifndef EFFECTTABLENAMELIST_H
#define EFFECTTABLENAMELIST_H


#define EV_DATASET_EFFECT_PRE "EV_EFFECT_"
#define EV_DATASET_EFFECTINS_PRE "EV_EFFECT_INS_"
#define EV_DATASET_EFFECTMATERIAL_PRE "EV_EFF_MAT_RES_"
#define EV_DATASET_EFFECTREF_PRE "EV_EFFECT_REF_"
#define EV_EFFECTLIB_EFFECT "EV_EFFECT"
#define EV_EFFECTLIB_EFFECTREF "EV_EFFECT_REF"
#define EV_EFFECTLIB_EFFECTMATR "EV_EFF_MAT_RES"
#define EV_EFFECTLIB_EFFECTTYPE "EV_EFFECTTYPE"

#define EV_EFFECTLIB_EFFECT_PK "EffectID"
#define EV_EFFECTLIB_EFFECTREF_PK "EffectRefID"
#define EV_EFFECTLIB_EFFECTMATR_PK "RES_ID"

#endif
