#ifndef __HeaderPrefix_H__
#define __HeaderPrefix_H__
#include "core/platform.h"
#if EV_COMPILER == EV_COMPILER_MSVC
/// Save warnings state
#pragma warning (push)
/// Turn off warnings generated by ev_int32 std templates
/// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4786)
/// Turn off warnings generated by ev_int32 std templates
/// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4503)
/// disable: "<type> needs to have dll-interface to be used by clients'
/// Happens on STL member variables which are not public therefore is ok
#pragma warning (disable : 4251)
/// disable: "non dll-interface class used as base for dll-interface class"
/// Happens when deriving from CSingleton because bug in compiler ignores
/// template export
#pragma warning (disable : 4275)
/// disable: "C++ CException Specification ignored"
/// This is because MSVC 6 did not implement all the C++ exception
/// specifications in the ANSI C++ draft.
#pragma warning( disable : 4290 )
/// disable: "no suitable definition provided for explicit template
/// instantiation request" Occurs in VC7 for no justifiable reason on all
/// #includes of CSingleton
#pragma warning( disable: 4661)
/// These show up on all C runtime lib code in VC8, disable since they clutter
/// the warnings with things we may not be able to do anything about (e.g.
/// generated code from nvparse etc). I doubt very much that these calls
/// will ever be actually removed from VC anyway, it would break too much code.
#pragma warning( disable: 4996)
/// disable: "conditional expression constant", always occurs on
/// EV_MUTEX_CONDITIONAL when no threading enabled
#pragma warning (disable : 201)
/// disable: "unreferenced formal parameter"
/// Many versions of VC have bugs which generate this error in cases where they shouldn't
#pragma warning (disable : 4100)
#endif

#endif


