using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

public static class EV_Symbol_ClassFactory
{
	public static void RegisterAll()
	{
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CArrowMarkerSymbol", new EarthView.World.Spatial.Display.ArrowMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CArrowMarkerSymbolProxy", new EarthView.World.Spatial.Display.ArrowMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CBarStatistics3DSymbol", new EarthView.World.Spatial.Display.BarStatistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CBarStatistics3DSymbolProxy", new EarthView.World.Spatial.Display.BarStatistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CBarStatisticsSymbol", new EarthView.World.Spatial.Display.BarStatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CBarStatisticsSymbolProxy", new EarthView.World.Spatial.Display.BarStatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CBillboard3DSymbol", new EarthView.World.Spatial.Display.Billboard3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CBillboard3DSymbolProxy", new EarthView.World.Spatial.Display.Billboard3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CCartographicLineSymbol", new EarthView.World.Spatial.Display.CartographicLineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CCartographicLineSymbolProxy", new EarthView.World.Spatial.Display.CartographicLineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFillSymbol", new EarthView.World.Spatial.Display.FillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFillSymbolProxy", new EarthView.World.Spatial.Display.FillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFontMarkerSymbol", new EarthView.World.Spatial.Display.FontMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFontMarkerSymbolProxy", new EarthView.World.Spatial.Display.FontMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFormattedTextSymbol", new EarthView.World.Spatial.Display.FormattedTextSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFormattedTextSymbolProxy", new EarthView.World.Spatial.Display.FormattedTextSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFresnelSurface3DSymbol", new EarthView.World.Spatial.Display.FresnelSurface3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CFresnelSurface3DSymbolProxy", new EarthView.World.Spatial.Display.FresnelSurface3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CGradientFillSymbol", new EarthView.World.Spatial.Display.GradientFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CGradientFillSymbolProxy", new EarthView.World.Spatial.Display.GradientFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CIcon3DSymbol", new EarthView.World.Spatial.Display.Icon3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CIcon3DSymbolProxy", new EarthView.World.Spatial.Display.Icon3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CLineFillSymbol", new EarthView.World.Spatial.Display.LineFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CLineFillSymbolProxy", new EarthView.World.Spatial.Display.LineFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CLineSymbol", new EarthView.World.Spatial.Display.LineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CLineSymbolProxy", new EarthView.World.Spatial.Display.LineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMarkerFillSymbol", new EarthView.World.Spatial.Display.MarkerFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMarkerFillSymbolProxy", new EarthView.World.Spatial.Display.MarkerFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMarkerSymbol", new EarthView.World.Spatial.Display.MarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMarkerSymbolProxy", new EarthView.World.Spatial.Display.MarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CModel3DSymbol", new EarthView.World.Spatial.Display.Model3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CModel3DSymbolProxy", new EarthView.World.Spatial.Display.Model3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiFillSymbol", new EarthView.World.Spatial.Display.MultiFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiFillSymbolProxy", new EarthView.World.Spatial.Display.MultiFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiLineSymbol", new EarthView.World.Spatial.Display.MultiLineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiLineSymbolProxy", new EarthView.World.Spatial.Display.MultiLineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiMarkerSymbol", new EarthView.World.Spatial.Display.MultiMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiMarkerSymbolProxy", new EarthView.World.Spatial.Display.MultiMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiSymbol", new EarthView.World.Spatial.Display.MultiSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CMultiSymbolProxy", new EarthView.World.Spatial.Display.MultiSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPhoto3DSymbol", new EarthView.World.Spatial.Display.Photo3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPhoto3DSymbolProxy", new EarthView.World.Spatial.Display.Photo3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPictureFillSymbol", new EarthView.World.Spatial.Display.PictureFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPictureFillSymbolProxy", new EarthView.World.Spatial.Display.PictureFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPictureMarkerSymbol", new EarthView.World.Spatial.Display.PictureMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPictureMarkerSymbolProxy", new EarthView.World.Spatial.Display.PictureMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPieStatistics3DSymbol", new EarthView.World.Spatial.Display.PieStatistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPieStatistics3DSymbolProxy", new EarthView.World.Spatial.Display.PieStatistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPieStatisticsSymbol", new EarthView.World.Spatial.Display.PieStatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CPieStatisticsSymbolProxy", new EarthView.World.Spatial.Display.PieStatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleFill3DSymbol", new EarthView.World.Spatial.Display.SimpleFill3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleFill3DSymbolProxy", new EarthView.World.Spatial.Display.SimpleFill3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleFillSymbol", new EarthView.World.Spatial.Display.SimpleFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleFillSymbolProxy", new EarthView.World.Spatial.Display.SimpleFillSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::KeyValuePair", new EarthView.World.Spatial.Display.KeyValuePairClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleLine3DSymbol", new EarthView.World.Spatial.Display.SimpleLine3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleLine3DSymbolProxy", new EarthView.World.Spatial.Display.SimpleLine3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleLineSymbol", new EarthView.World.Spatial.Display.SimpleLineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleLineSymbolProxy", new EarthView.World.Spatial.Display.SimpleLineSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleMarkerSymbol", new EarthView.World.Spatial.Display.SimpleMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleMarkerSymbolProxy", new EarthView.World.Spatial.Display.SimpleMarkerSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleTextSymbol", new EarthView.World.Spatial.Display.SimpleTextSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSimpleTextSymbolProxy", new EarthView.World.Spatial.Display.SimpleTextSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStackedStatistics3DSymbol", new EarthView.World.Spatial.Display.StackedStatistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStackedStatistics3DSymbolProxy", new EarthView.World.Spatial.Display.StackedStatistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStackedStatisticsSymbol", new EarthView.World.Spatial.Display.StackedStatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStackedStatisticsSymbolProxy", new EarthView.World.Spatial.Display.StackedStatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::TagStatistics3DSymbol", new EarthView.World.Spatial.Display.TagStatistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStatistics3DSymbol", new EarthView.World.Spatial.Display.Statistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStatistics3DSymbolProxy", new EarthView.World.Spatial.Display.Statistics3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStatisticsSymbol", new EarthView.World.Spatial.Display.StatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CStatisticsSymbolProxy", new EarthView.World.Spatial.Display.StatisticsSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSVGMarkerSymbol", new EarthView.World.Spatial.Display.SvgmarkersymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSVGMarkerSymbolProxy", new EarthView.World.Spatial.Display.SvgmarkersymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbol", new EarthView.World.Spatial.Display.SymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolProxy", new EarthView.World.Spatial.Display.SymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CTextureInfo", new EarthView.World.Spatial.Display.TextureInfoClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbol3D", new EarthView.World.Spatial.Display.Symbol3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbol3DProxy", new EarthView.World.Spatial.Display.Symbol3DClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolDisplay", new EarthView.World.Spatial.Display.SymbolDisplayClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolDisplayProxy", new EarthView.World.Spatial.Display.SymbolDisplayClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolFactory", new EarthView.World.Spatial.Display.SymbolFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolFactoryProxy", new EarthView.World.Spatial.Display.SymbolFactoryClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolLayer", new EarthView.World.Spatial.Display.SymbolLayerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolLayerProxy", new EarthView.World.Spatial.Display.SymbolLayerClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolRenderer", new EarthView.World.Spatial.Display.SymbolRendererClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CSymbolRendererProxy", new EarthView.World.Spatial.Display.SymbolRendererClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CTextSymbol", new EarthView.World.Spatial.Display.TextSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CTextSymbolProxy", new EarthView.World.Spatial.Display.TextSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CTextureFill3DSymbol", new EarthView.World.Spatial.Display.TextureFill3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CTextureFill3DSymbolProxy", new EarthView.World.Spatial.Display.TextureFill3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CTextureLine3DSymbol", new EarthView.World.Spatial.Display.TextureLine3DSymbolClassFactory());
		EarthView.World.Core.GlobalClassFactoryMap.Put("EarthView::World::Spatial::Display::CTextureLine3DSymbolProxy", new EarthView.World.Spatial.Display.TextureLine3DSymbolClassFactory());
	}
}

